### ISSUE TITLE
Duplicate classes when building release version

### ISSUE THREAD

**Issue by Abdelkareem-dev** [juicycleff/flutter-unity-view-widget#241]
There is an issue when creating a release with Flutter unity version 2.0.0+2,
`flutter build apk --release --no-shrink`
showed this error:
```
E:\Elite1.0.1\flutter_application\build\unity-classes\.transforms\b5e8b22986bf7a9530f908642927ff85\jetified-unity-classes\classes.dex: D8: Type com.uni
ty3d.player.GoogleARCoreApi is defined multiple times: E:\Elite1.0.1\flutter_application\build\unity-classes\.transforms\b5e8b22986bf7a9530f908642927ff
85\jetified-unity-classes\classes.dex, E:\Elite1.0.1\flutter_application\build\app\intermediates\external_libs_dex\release\out\classes2.dex
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Type com.unity3d.player.GoogleARCoreApi is defined multiple times: E:\Elite1.0.1\flutter_application\build\unity-classes\.transforms\b5e8b22986bf7a9530
f908642927ff85\jetified-unity-classes\classes.dex, E:\Elite1.0.1\flutter_application\build\app\intermediates\external_libs_dex\release\out\classes2.dex
        at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:132)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:119)
        at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
        at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:445)
        at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:348)
        at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
        at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
        at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.O.a(:65)
        at com.android.tools.r8.D8.run(:11)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:117)
        ... 34 more
Caused by: com.android.tools.r8.utils.b: Error: E:\Elite1.0.1\flutter_application\build\unity-classes\.transforms\b5e8b22986bf7a9530f908642927ff85\jeti
fied-unity-classes\classes.dex, Type com.unity3d.player.GoogleARCoreApi is defined multiple times: E:\Elite1.0.1\flutter_application\build\unity-classe
s\.transforms\b5e8b22986bf7a9530f908642927ff85\jetified-unity-classes\classes.dex, E:\Elite1.0.1\flutter_application\build\app\intermediates\external_l
ibs_dex\release\out\classes2.dex
        at com.android.tools.r8.utils.y0.a(:21)
        at com.android.tools.r8.utils.x0.a(:30)
        at com.android.tools.r8.utils.x0.a(:10)
        at java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:1990)
        at com.android.tools.r8.utils.x0.a(:6)
        at com.android.tools.r8.graph.A0$c.a(:6)
        at com.android.tools.r8.dex.a.a(:85)
        at com.android.tools.r8.dex.a.a(:12)
        at com.android.tools.r8.D8.d(:6)
        at com.android.tools.r8.D8.b(:1)
        at com.android.tools.r8.utils.O.a(:30)
        ... 36 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Type com.unity3d.player.GoogleARCoreApi is defined multiple times: E:\Elite1.0.1\flutter_application\build\unity-classes\.transforms\b5e8b22986bf7
a9530f908642927ff85\jetified-unity-classes\classes.dex, E:\Elite1.0.1\flutter_application\build\app\intermediates\external_libs_dex\release\out\classes
2.dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 48s
```
Also `flutter build apk --release`

Showed this error too:
```
C:\Users\Kimo Hero\.gradle\caches\transforms-2\files-2.1\e3a4c68202b11338740debdbaa454163\jetified-unity-classes.jar: R8: Type org.fmod.a is defined mu
ltiple times: C:\Users\Kimo Hero\.gradle\caches\transforms-2\files-2.1\e3a4c68202b11338740debdbaa454163\jetified-unity-classes.jar:org/fmod/a.class, E:
\Elite1.0.1\flutter_application\build\unity-classes\.transforms\c1a49aac15caac4be4d809a44280e18e\jetified-unity-classes.jar:org/fmod/a.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by juicycleff** [comment]
@Abdelkareem-dev you need to make sure you are not importing unity export libs mutliple times

**Comment by Abdelkareem-dev** [comment]
@juicycleff yeah you are right, thank you.
I was importing the same library in `settings.gradle`, I just commented them 
```
//include ':UnityARCore'
//include ':unityandroidpermissions'
//include ':unity-classes'
//include ':NativeShare'
//include ':NativeGallery'
//include ':NativeCamera'
//include ':ARPresto'
//include ':arcore_client'
include ':app'

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}


include ":unityLibrary"
project(":unityLibrary").projectDir = file("./unityLibrary")
```
