### ISSUE TITLE
 java.lang.RuntimeException: platformViewsController must be set before attempting to begin the frame

### ISSUE THREAD

**Issue by OGmetamonkey** [juicycleff/flutter-unity-view-widget#274]
Describe the bug:
Tried upgrading to the latest implementation of the flutter unity widget. Previous working implementation was ^0.1.6+8. 

To Reproduce

1. Add flutter_unity_widget: ^3.0.1 to the flutter project as specified in the read me, including the addition of 'FlutterUnityPackage.unitypackage
2. Explicitly declare NDK directory in Unity Library build.gradle file (Prior to this, got a bug as specified in [issue 273](https://github.com/juicycleff/flutter-unity-view-widget/issues/273).
3. Open in Unity and build to Android
4. Try to build the flutter project to android device in debugger mode.

Expected behavior:
Expected the app to build successfully as it did when using flutter unity widget version ^0.1.6+8

Versions
Flutter: 1.22.5
Dart: 2.10.4
Flutter unity widget: 3.0.1
Unity: 2020.1.16f1
Unity Hub: 2.4.2
Android Device: Nexus 5x using Android 8.1.0

Debug Log:

> I/IL2CPP (30164): JNI_OnLoad
> I/Choreographer(30164): Skipped 81 frames! The application may be doing too much work on its main thread.
> E/flutter (30164): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.RuntimeException: platformViewsController must be set before attempting to begin the frame
> E/flutter (30164): at io.flutter.embedding.engine.FlutterJNI.onBeginFrame(FlutterJNI.java:842)
> E/flutter (30164): at android.os.MessageQueue.nativePollOnce(Native Method)
> E/flutter (30164): at android.os.MessageQueue.next(MessageQueue.java:325)
> E/flutter (30164): at android.os.Looper.loop(Looper.java:142)
> E/flutter (30164): at android.app.ActivityThread.main(ActivityThread.java:6494)
> E/flutter (30164): at java.lang.reflect.Method.invoke(Native Method)
> E/flutter (30164): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> E/flutter (30164): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> E/flutter (30164):
> F/flutter (30164): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1228)] Check failed: CheckException(env).
> I/flutter (30164): Unity is created!!
> I/flutter (30164): *********************************************
> I/flutter (30164): ** flutter unity controller setup complete **
> I/flutter (30164): *********************************************
> Lost connection to device.
> Exited (sigterm)

**Comment by OGmetamonkey** [comment]
Update: I attempted downgrading to Unity 2019.3.14f1. Got the same error and crash. It did, however, eliminate the need to declare the NDK directory in the unity library build.gradle.

> E/flutter (11958): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] 
> java.lang.RuntimeException: platformViewsController must be set before attempting to begin the frame
> E/flutter (11958): 	at io.flutter.embedding.engine.FlutterJNI.onBeginFrame(FlutterJNI.java:842)
> E/flutter (11958): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/flutter (11958): 	at android.os.MessageQueue.next(MessageQueue.java:325)
> E/flutter (11958): 	at android.os.Looper.loop(Looper.java:142)
> E/flutter (11958): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
> E/flutter (11958): 	at java.lang.reflect.Method.invoke(Native Method)
> E/flutter (11958): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
> E/flutter (11958): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> E/flutter (11958): 
> F/flutter (11958): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1228)] Check failed: CheckException(env). 
> I/flutter (11958): Unity is created!!
> I/flutter (11958): *********************************************
> I/flutter (11958): ** flutter unity controller setup complete **
> I/flutter (11958): *********************************************
>

**Comment by OGmetamonkey** [comment]
Still having this problem. Please help!

**Comment by guoguoguilai** [comment]
The same issue. Any update?
