### ISSUE TITLE
Application Crashing in Android 

### ISSUE THREAD

**Issue by kanhaiyhacker** [juicycleff/flutter-unity-view-widget#298]
**Describe the bug**
When used Joystick in Unity Application, the Application is crashing with the below issue.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.stone_game_integration, PID: 19402
    android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:842)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
        at android.app.Dialog.show(Dialog.java:329)
        at bitter.jnibridge.JNIBridge.invoke(Native Method)
        at bitter.jnibridge.JNIBridge$a.invoke(Unknown Source:20)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy8.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by DroneMesh** [comment]
Line 99 in with_arkit_screen.dart

is set to 

```
isARScene: false,
```
Change it to 
```
isARScene: true,
```

**Comment by juicycleff** [comment]
Fixed in v4
