### ISSUE TITLE
Flutter unity communication issue

### ISSUE THREAD

**Issue by anass-naoushi** [juicycleff/flutter-unity-view-widget#300]
I am new to unity and I have a scene that I must integrate into a flutter app as part of my job (An AR scene). I connected the scene successfully but the problem is that the communication between flutter and unity is not working . The `onUnitySceneLoaded `& the `onUnityMessage `are not working. Only the `onUnityCreated `is working and displaying prints. To my understanding I need to add some code to the unity scene to make its messages be recognized by flutter and the Flutter unity package . So lets ignore this for know and investigate why is `onUnitySceneLoaded `not working. Shouldn't it work out of the box automatically. This function will work directly after the unity scene appears right ? Here is my entire flutter code for the unity screen:

**To Reproduce Use the Following Code**
```
import 'package:flutter/material.dart';
import 'package:flutter_unity_widget/flutter_unity_widget.dart';

class UnityMainScene extends StatefulWidget {
  UnityMainScene({Key key}) : super(key: key);

  @override
  _UnityMainSceneState createState() => _UnityMainSceneState();
}

class _UnityMainSceneState extends State<UnityMainScene> {
  UnityWidgetController _unityWidgetController;

  @override
  void initState() {
    super.initState();
  }

  

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Container(
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.topLeft,
              end: Alignment(0.8, 0.0),
              colors: [
                const Color.fromRGBO(109, 180, 194, 1),
                const Color.fromRGBO(83, 116, 234, 1),
              ],
            ),
          ),
          child: Column(
            children: [
              Expanded(
                child: Container(
                  clipBehavior: Clip.antiAlias,
                  width: MediaQuery.of(context).size.width,
                  height: MediaQuery.of(context).size.height,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(50),
                        bottomRight: Radius.circular(50)),
                  ),
                  child: UnityWidget(
                    onUnityCreated: _onUnityCreated,
                    isARScene: true,
                    onUnityMessage: onUnityMessage,
                    onUnitySceneLoaded: onUnitySceneLoaded,
                    fullscreen: false,
                  ),
                ),
              ),
              Container(
                padding: const EdgeInsets.all(20.0),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: <Widget>[
                    GestureDetector(
                      child: Image.asset('assets/images/wallet.png'),
                      onTap: () => Navigator.pop(context),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  void onUnityMessage(message) {
    print('unity message recieved by anass');
    print('Received message from unity: ${message.toString()}');
  }

  void onUnitySceneLoaded(SceneLoaded scene) {
    print('unity scene loaded by anass');
    print('Received scene loaded from unity: ${scene.name}');
    print('Received scene loaded from unity buildIndex: ${scene.buildIndex}');
  }

  // Callback that connects the created controller to the unity controller
  void _onUnityCreated(controller) {
    print('unity scene created by anass');
    this._unityWidgetController = controller;
  }
}

```

**Expected behavior**
At least the `onUnitySceneLoaded ` to work

**Flutter Doctor -v Output**
```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19041.746], locale en-US)
    • Flutter version 1.22.5 at D:\flutter-src\flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Alpha\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by invlabz** [comment]
@anass-naoushi  Did you able to solve the issue? I am also facing same issue.

**Comment by anass-naoushi** [comment]
> @anass-naoushi Did you able to solve the issue? I am also facing same issue.

NO I was not able t solve it in any way. One possibility is to move all unity related functionalities to the unity project itself

**Comment by anass-naoushi** [comment]
@juicycleff  any idea why this communication error might happen ??

**Comment by juicycleff** [comment]
You need to setup the unity messaging modules properly in your unity project.

**Comment by anass-naoushi** [comment]
@juicycleff  we need to set the messaging module even for `onUnitySceneLoaded ` ??

**Comment by anass-naoushi** [comment]
@juicycleff  we need to set the messaging module even for `onUnitySceneLoaded ` ??

**Comment by juicycleff** [comment]
@anass-naoushi did you properly import the unitypackage https://github.com/juicycleff/flutter-unity-view-widget/tree/master/scripts. Please look at the example project to see if you are missing something

**Comment by invlabz** [comment]
@juicycleff unitypackage is same as the example project. build.gradle files and manifest files are almost same. Yet facing communication issue.

onUnityCreated is working fine.
But onUnitySceneLoaded is not working, with below log and exception.
```
Launching lib\main.dart on vivo 1935 in debug mode...
 lib\main.dart
Building libil2cpp.so with AndroidToolChain
	Output directory: D:\Programming\invlabz\app\invlabz\android\unityLibrary\src\main\jniLibs\armeabi-v7a
	Cache directory: D:\Programming\invlabz\app\invlabz\android\unityLibrary\build\il2cpp_armeabi-v7a_Release\il2cpp_cache
ObjectFiles: 225 of which compiled: 225
	Time Compile: 31058 milliseconds Lump_libil2cpp_vm.cpp
	Time Compile: 28510 milliseconds Il2CppCCalculateTypeValues.cpp
	Time Compile: 22700 milliseconds Il2CppInvokerTable.cpp
	Time Compile: 20975 milliseconds Lump_libil2cpp_icalls.cpp
	Time Compile: 20074 milliseconds System5.cpp
	Time Compile: 19634 milliseconds Generics.cpp
	Time Compile: 18347 milliseconds Generics2.cpp
	Time Compile: 18271 milliseconds mscorlib1.cpp
	Time Compile: 17085 milliseconds GenericMethods.cpp
	Time Compile: 16846 milliseconds System.cpp
Total compilation time: 182625 milliseconds.
Total link time: 8737 milliseconds.
Cleaned up 0 object files.
Building libil2cpp.so with AndroidToolChain
	Output directory: D:\Programming\invlabz\app\invlabz\android\unityLibrary\src\main\jniLibs\arm64-v8a
	Cache directory: D:\Programming\invlabz\app\invlabz\android\unityLibrary\build\il2cpp_arm64-v8a_Release\il2cpp_cache
ObjectFiles: 225 of which compiled: 225
	Time Compile: 32678 milliseconds Lump_libil2cpp_vm.cpp
	Time Compile: 21815 milliseconds Lump_libil2cpp_icalls.cpp
	Time Compile: 20391 milliseconds Il2CppInvokerTable.cpp
	Time Compile: 20354 milliseconds Generics2.cpp
	Time Compile: 19722 milliseconds mscorlib2.cpp
	Time Compile: 19569 milliseconds mscorlib19.cpp
	Time Compile: 19531 milliseconds Il2CppCCalculateFieldValues.cpp
	Time Compile: 18851 milliseconds mscorlib8.cpp
	Time Compile: 18826 milliseconds UnityEngine.UI.cpp
	Time Compile: 18332 milliseconds Generics5.cpp
Total compilation time: 189520 milliseconds.
Total link time: 12710 milliseconds.
Cleaned up 0 object files.
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:51287/EhPjTnlDQO4=/ws
I/IL2CPP  (17169): JNI_OnLoad
I/Choreographer(17169): Skipped 66 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer(17169): Davey! duration=1130ms; Flags=1, IntendedVsync=143745540720391, Vsync=143746640720347, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=143746642944173, AnimationStart=143746643047193, PerformTraversalsStart=143746646869745, DrawStart=143746665062141, SyncQueued=143746665943495, SyncStart=143746666366620, IssueDrawCommandsStart=143746666443079, SwapBuffers=143746669813183, FrameCompleted=143746671520475, DequeueBufferDuration=2080000, QueueBufferDuration=1136000,
W/Gralloc3(17169): allocator 3.x is not supported
I/flutter (17169): ############################################
I/flutter (17169): *********************************************
I/flutter (17169): ** flutter unity controller setup complete **
I/flutter (17169): *********************************************
I/flutter (17169): false
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): Failed to handle method call
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): 	at com.xraph.plugins.flutterunitywidget.FlutterUnityViewController.onMethodCall(FlutterUnityViewController.java:163)
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): 	at android.os.MessageQueue.next(MessageQueue.java:340)
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): 	at android.app.ActivityThread.main(ActivityThread.java:7752)
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
E/MethodChannel#plugins.xraph.com/unity_view_0(17169): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/DartMessenger(17169): Uncaught exception in binary message listener
E/DartMessenger(17169): java.lang.IllegalStateException: Reply already submitted
E/DartMessenger(17169): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/DartMessenger(17169): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:253)
E/DartMessenger(17169): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/DartMessenger(17169): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/DartMessenger(17169): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(17169): 	at android.os.MessageQueue.next(MessageQueue.java:340)
E/DartMessenger(17169): 	at android.os.Looper.loop(Looper.java:183)
E/DartMessenger(17169): 	at android.app.ActivityThread.main(ActivityThread.java:7752)
E/DartMessenger(17169): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(17169): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
E/DartMessenger(17169): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
W/example.invlab(17169): Accessing hidden method Ljava/lang/invoke/MethodHandles$Lookup;-><init>(Ljava/lang/Class;I)V (greylist, reflection, allowed)
I/Unity   (17169): SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 7608mb
I/Unity   (17169):
I/Unity   (17169): SystemInfo ARM big.LITTLE configuration: 4 big (mask: 0xf0), 4 little (mask: 0xf)
I/Unity   (17169):
I/Unity   (17169): ApplicationInfo com.example.invlabz version 1.0.0 build a4a54356-2853-4335-8a32-1314a600ac2c
I/Unity   (17169):
I/Unity   (17169): Built from '2020.2/release' branch, Version '2020.2.1f1 (270dd8c3da1c)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Enabled'
I/Unity   (17169):
E/libprocessgroup(17169): set_timerslack_ns write failed: Operation not permitted
I/chatty  (17169): uid=10182(com.example.invlabz) UnityMain identical 14 lines
E/libprocessgroup(17169): set_timerslack_ns write failed: Operation not permitted
I/Unity   (17169): Company Name: DefaultCompany
I/Unity   (17169): Product Name: fgen
D/Unity   (17169):  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_ldr GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled
D/Unity   (17169): _render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT_sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_par
D/Unity   (17169): ams GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_texture_foveated_subsampled_layout GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density GL_QCOM_YUV_texture_gather
I/SwappyDisplayManager(17169): Starting looper thread
D/        (17169): PlayerBase::PlayerBase()
D/        (17169): TrackPlayerBase::TrackPlayerBase()
I/libOpenSLES(17169): Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
D/AudioTrack(17169): set(): streamType 3, sampleRate 48000, format 0x1, channelMask 0x3, frameCount 0, flags #104, notificationFrames -21, sessionId 24729, transferType 0, uid -1, pid -1
D/AudioTrack(17169): getpackName client name com.example.invlabz(17169)
W/AudioTrack(17169): set(): notificationFrames=-21 clamped to the range -1 to -8
D/AudioTrack(17169): get APPSharePck , clientName com.example.invlabz  appSharePck NULL
D/AudioSystem(17169): client pid (17169)
D/AudioSystem(17169): isCommunicatingAPP:0, pid: 17169
I/AudioTrack(17169): createTrack_l(0): AUDIO_OUTPUT_FLAG_FAST successful; frameCount 0 -> 1536
V/MediaRouter(17169): startMonitoringRoutes: android.media.MediaRouter$Static@87913fc
D/MediaRouter(17169): Adding route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
V/MediaRouter(17169): Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
D/MediaRouter(17169): updateAudioRoutes currentSystemRoute :RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null },mDefaultAudioVideo:RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
D/MediaRouter(17169): selectRouteStatic  set mSelectedRoute:RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
D/        (17169): PlayerBase::stop() from IPlayer
D/AudioTrack(17169): stop(3055): called with 1565952 frames delivered
D/MediaRouter(17169): onRestoreRoute() : route=RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
V/MediaRouter(17169): Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
D/MediaRouter(17169): updateAudioRoutes currentSystemRoute :RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null },mDefaultAudioVideo:RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
D/        (17169): PlayerBase::stop() from IPlayer
D/AudioTrack(17169): stop(3055): called with 1458816 frames delivered
D/MediaRouter(17169): onRestoreRoute() : route=RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
V/MediaRouter(17169): Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
D/MediaRouter(17169): updateAudioRoutes currentSystemRoute :RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null },mDefaultAudioVideo:RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
D/        (17169): PlayerBase::stop() from IPlayer
D/AudioTrack(17169): stop(3055): called with 2087616 frames delivered

```

**Comment by invlabz** [comment]
I have solved the problem, I had use seperate functions and then point it to callBacks instead insilne functions.

**Comment by Darkmax** [comment]
> I have solved the problem, I had use seperate functions and then point it to callBacks instead insilne functions.

I'm having a similar issue on ios, but not in android. When I enter to unity screen for a second time (is not happening the first time I enter to the unity flutter screen) I can send information from flutter to unity, but from unity to flutter I can't send messages.
How exactly do you solve the issue, maybe I can solve my issue this way.

**Comment by juicycleff** [comment]
Please use the latest unity package and the latest package release. Should fix this problem

**Comment by LuoLuoDev** [comment]
> I have solved the problem, I had use seperate functions and then point it to callBacks instead insilne functions.

can you show more details?

**Comment by 7osssam** [comment]
> I have solved the problem, I had use seperate functions and then point it to callBacks instead insilne functions.

More details will be appreciated

**Comment by omarsalem15** [comment]
can you help me 
how to make a button in Flutter screen to open a specific scene in unity
