### ISSUE TITLE
Android app crashes on returning to Unity screen

### ISSUE THREAD

**Issue by jain-aayush1123** [juicycleff/flutter-unity-view-widget#323]
When I leave unity game screen and return to it, the app crashes. Moreover the game scene is running in the background as I can hear the game music playing which should ideally stop. And when I return to the game, the whole app crashes.

**Comment by mrdavidrees** [comment]
I am experiencing this as well. These are my crash logs.

```
D/mali_winsys(28955): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1080x2076]-format:1
D/SurfaceView(28955): BG show() Surface(name=Background for - SurfaceView - com.example.app/com.example.app.MainActivity@2776aa6@0) android.view.SurfaceView{2776aa6 VFE...... ........ 0,0-1080,1173 #7f0700f0 app:id/unitySurfaceView}
D/SurfaceView(28955): surfaceDestroyed 1 android.view.SurfaceView{2776aa6 VFE...... ........ 0,0-1080,1173 #7f0700f0 app:id/unitySurfaceView}
D/SurfaceView(28955): BG destroy() Surface(name=Background for - SurfaceView - com.example.app/com.example.app.MainActivity@2776aa6@0) android.view.SurfaceView{2776aa6 VFE...... ........ 0,0-1080,1173 #7f0700f0 app:id/unitySurfaceView}
E/Surface (28955): dequeueBuffer: IGraphicBufferProducer::requestBuffer failed: -19
E/vulkan  (28955): dequeueBuffer failed: No such device (-19)
D/ViewRootImpl@b0e8928[MainActivity](28955): ViewPostIme pointer 1
E/CRASH   (28955): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
E/CRASH   (28955): Version '2019.4.16f1 (e05b6e02d63e)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
E/CRASH   (28955): Build fingerprint: 'samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU2CRED:user/release-keys'
E/CRASH   (28955): Revision: '10'
E/CRASH   (28955): ABI: 'arm64'
E/CRASH   (28955): Timestamp: 2021-02-24 10:58:18+1000
E/CRASH   (28955): pid: 28955, tid: 29936, name: UnityGfxDeviceW  >>> com.example.app <<<
E/CRASH   (28955): uid: 10600
E/CRASH   (28955): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
E/CRASH   (28955): Cause: null pointer dereference
E/CRASH   (28955):     x0  0000000000000000  x1  00000072927fb120  x2  0000000000000002  x3  0000000000000400
E/CRASH   (28955):     x4  0000000000000100  x5  0000000000000001  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
E/CRASH   (28955):     x8  00000072106aa400  x9  000000000000afc5  x10 0000000000000010  x11 0000000000000000
E/CRASH   (28955):     x12 00000000000001ff  x13 ffffffffffffffff  x14 ff00000000000000  x15 ffffffffffffffff
E/CRASH   (28955):     x16 00000072a58f6968  x17 000000731a93fcd0  x18 0000000000000001  x19 000000721046b7c0
E/CRASH   (28955):     x20 00000072106aa400  x21 000000721046b7c0  x22 0000000000000007  x23 000000721047c578
E/CRASH   (28955):     x24 0000000000000001  x25 0000000000002713  x26 00000072927fb588  x27 0000007210461220
E/CRASH   (28955):     x28 00000071b0000388  x29 00000072927fb420
E/CRASH   (28955):     sp  00000072927fb120  lr  00000072a4dd42e8  pc  00000072a4dd4308
E/CRASH   (28955):
E/CRASH   (28955): backtrace:
E/CRASH   (28955):       #00 pc 0000000000385308  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libunity.so (BuildId: 0d21b26df25b189dc0b8910f3ec5d5c0eeceb785)
E/CRASH   (28955):       #01 pc 00000000003920e8  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libunity.so (BuildId: 0d21b26df25b189dc0b8910f3ec5d5c0eeceb785)
E/CRASH   (28955):       #02 pc 0000000000375c10  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libunity.so (BuildId: 0d21b26df25b189dc0b8910f3ec5d5c0eeceb785)
E/CRASH   (28955):       #03 pc 0000000000717efc  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libunity.so (BuildId: 0d21b26df25b189dc0b8910f3ec5d5c0eeceb785)
E/CRASH   (28955):       #04 pc 00000000007207c0  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libunity.so (BuildId: 0d21b26df25b189dc0b8910f3ec5d5c0eeceb785)
E/CRASH   (28955):       #05 pc 0000000000717b98  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libunity.so (BuildId: 0d21b26df25b189dc0b8910f3ec5d5c0eeceb785)
E/CRASH   (28955):       #06 pc 0000000000283318  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libunity.so (BuildId: 0d21b26df25b189dc0b8910f3ec5d5c0eeceb785)
E/CRASH   (28955):       #07 pc 000000000006de34  /system/lib64/libc.so (__pthread_start(void*)+36) (BuildId: 15d02ec170049aef52a051cd6c6dee67)
E/CRASH   (28955):       #08 pc 000000000001f9a4  /system/lib64/libc.so (__start_thread+68) (BuildId: 15d02ec170049aef52a051cd6c6dee67)
E/BufferItemConsumer(28955): [ImageReader-1080x2076f1m3-28955-0] Failed to release buffer: Unknown error -1 (1)
D/ViewRootImpl@b0e8928[MainActivity](28955): ViewPostIme pointer 0
D/ViewRootImpl@b0e8928[MainActivity](28955): ViewPostIme pointer 1
E/CRASH   (28955): other thread is trapped; signum = 11
E/flutter (28955): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
E/flutter (28955): Version '2019.4.16f1 (e05b6e02d63e)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
E/flutter (28955): Build fingerprint: 'samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU2CRED:user/release-keys'
E/flutter (28955): Revision: '10'
E/flutter (28955): ABI: 'arm64'
E/flutter (28955): Timestamp: 2021-02-24 10:58:18+1000
E/flutter (28955): pid: 28955, tid: 29936, name: UnityGfxDeviceW  >>> com.example.app <<<
E/flutter (28955): uid: 10600
E/flutter (28955): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
E/flutter (28955): Cause: null pointer dereference
E/flutter (28955):     x0  0000000000000000  x1  00000072927fb120  x2  0000000000000002  x3  0000000000000400
E/flutter (28955):     x4  0000000000000100  x5  0000000000000001  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
E/flutter (28955):     x8  00000072106aa400  x9  000000000000afc5  x10 0000000000000010  x11 0000000000000000
E/flutter (28955):     x12 00000000000001ff  x13 ffffffffffffffff  x14 ff00000000000000  x15 ffffffffffffffff
E/flutter (28955):     x16 00000072a58f6968  x17 000000731a93fcd0  x18 0000000000000001  x19 000000721046b7c0
E/flutter (28955):     x20 00000072106aa400  x21 000000721046b7c0  x22 0000000000000007  x23 000000721047c578
E/flutter (28955):     x24 0000000000000001  x25 0000000000002713  x26 00000072927fb588  x27 0000007210461220
E/flutter (28955):     x28 00000071b0000388  x29 00000072927fb420
E/flutter (28955):     sp  00000072927fb120  lr  00000072a4dd42e8  pc  00000072a4dd4308
E/flutter (28955):
E/flutter (28955): backtrace:
E/flutter (28955):       #00 pc 0000000000385308  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libunity.so (BuildId: 0d21b26df25b189dc0b8910f3ec5d5c0eeceb785)
E/flutter (28955):       #01 pc 00000000003920e8  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libunity.so (BuildId: 0d21b26df25b189dc0b8910f3ec5d5c0eeceb785)
E/flutter (28955):       #02 pc 0000000000375c10  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libunity.so (BuildId: 0d21b26df25b189dc0b8910f3ec5d5c0eeceb785)
E/flutter (28955):       #03 pc 0000000000717efc  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libunity.so (BuildId: 0d21b26df25b189dc0b8910f3ec5d5c0eeceb785)
E/flutter (28955):       #04 pc 00000000007207c0  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libunity.so (BuildId: 0d21b26df25b189dc0b8910f3ec5d5c0eeceb785)
E/flutter (28955):       #05 pc 0000000000717b98  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libunity.so (BuildId: 0d21b26df25b189dc0b8910f3ec5d5c0eeceb785)
E/flutter (28955):       #06 pc 0000000000283318  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libunity.so (BuildId: 0d21b26df25b189dc0b8910f3ec5d5c0eeceb785)
E/flutter (28955):       #07 pc 000000000006de34  /system/lib64/libc.so (__pthread_start(void*)+36) (BuildId: 15d02ec170049aef52a051cd6c6dee67)
E/flutter (28955):       #08 pc 000000000001f9a4  /system/lib64/libc.so (__start_thread+68) (BuildId: 15d02ec170049aef52a051cd6c6dee67)
E/flutter (28955):
E/flutter (28955): 	at libunity.0x385308(Native Method)
E/flutter (28955): 	at libunity.0x3920e8(Native Method)
E/flutter (28955): 	at libunity.0x375c10(Native Method)
E/flutter (28955): 	at libunity.0x717efc(Native Method)
E/flutter (28955): 	at libunity.0x7207c0(Native Method)
E/flutter (28955): 	at libunity.0x717b98(Native Method)
E/flutter (28955): 	at libunity.0x283318(Native Method)
E/flutter (28955): 	at libc.__pthread_start(void*)(__pthread_start:36)
E/flutter (28955): 	at libc.__start_thread(__start_thread:68)
E/flutter (28955):
F/flutter (28955): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env).
E/CRASH   (28955): Forwarding signal 6
F/libc    (28955): Fatal signal 6 (SIGABRT), code -6 in tid 28955 (est.exampleapp)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/dreamltexx/dreamlte:8.0.0/R16NW/G950FXXU2CRED:user/release-keys'
Revision: '10'
ABI: 'arm64'
pid: 28955, tid: 28955, name: est.exampleapp  >>> com.example.app <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env).
'
    x0   0000000000000000  x1   000000000000711b  x2   0000000000000006  x3   0000000000000008
    x4   0000000000008000  x5   0000000000008000  x6   0000000000008000  x7   0080000000000000
    x8   0000000000000083  x9   3ead2e4161657d4b  x10  0000000000000000  x11  0000000000000000
    x12  ffffffffffffffff  x13  0000000000000008  x14  ffffffffffffffff  x15  00006bace7612b60
    x16  000000731a9a22f8  x17  000000731a94283c  x18  000000731d92b0f0  x19  000000000000711b
    x20  000000000000711b  x21  0000007fde68ed58  x22  0000007318625c08  x23  00000072e8c47018
    x24  000000000000003a  x25  0000000000000001  x26  000000000000003a  x27  0000000000000001
    x28  0000000000000001  x29  0000007fde68ed40  x30  000000731a8ef05c
    sp   0000007fde68ed00  pc   000000731a942844  pstate 0000000060000000
backtrace:
    #00 pc 0000000000071844  /system/lib64/libc.so (tgkill+8)
    #01 pc 000000000001e058  /system/lib64/libc.so (abort+88)
    #02 pc 0000000000019244  /data/app/com.example.app-0lMWyh92d4WaEXsKKE6GUQ==/lib/arm64/libflutter.so (offset 0x126e000)
Lost connection to device.
Exited (sigterm)
```

**Comment by tomascimadorook** [comment]
Same Here, @juicycleff Do you have any clue of what is probably happening?

**Comment by jain-aayush1123** [comment]
Probably not closing and then opening correctly. I am getting the same crash logs as  @mrdavidrees

**Comment by tomascimadorook** [comment]
Hi, @jain-aayush1123 What do you mean by closing and openint? Are you talking about the widget or inside the Unity project?

**Comment by jain-aayush1123** [comment]
> Hi, @jain-aayush1123 What do you mean by closing and openint? Are you talking about the widget or inside the Unity project?
So the filter unity widget is embedded within a flutter screen right. So I run the app, navigate to flutter unity widget screen, run the game. Navigate to a new screen and try to revisit the game screen. App crashes. Dumps the thread log.

**Comment by tomascimadorook** [comment]
I temporally solved it disabling Multithreaded Rendering in Player Settings, take a look at this issue  https://github.com/juicycleff/flutter-unity-view-widget/issues/299

**Comment by MtPython** [comment]
@jain-aayush1123, could you test whether the scene is still running in the background after applying the mentioned 
>disable Multithreaded Rendering in Player Settings

fix?

**Comment by jain-aayush1123** [comment]
Ya disabling multithreading seems to resolve the issues. Thanks!

**Comment by nikiforospertselis** [comment]
I have the same issue. I have already disable multithreading but the problem still exists. Any idea?
