### ISSUE TITLE
Android JNI cannot find Activity when rendering UnityWidget

### ISSUE THREAD

**Issue by clemens773** [juicycleff/flutter-unity-view-widget#336]
I'm currently facing the following issue:
I have exported my Unity project via `Flutter > Export Android`. I have also written a very simple app to test the widget. The app builds correctly, but as soon as Flutter tries to render the widget, I encounter the following error:
```
F/art     (26784): art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: can't call android.view.WindowManager android.app.Activity.getWindowManager() on null object
F/art     (26784): art/runtime/java_vm_ext.cc:470]     in call to CallObjectMethodV
F/art     (26784): art/runtime/java_vm_ext.cc:470]     from boolean com.unity3d.player.UnityPlayer.nativeRender()
F/art     (26784): art/runtime/java_vm_ext.cc:470] "UnityMain" prio=5 tid=18 Runnable
F/art     (26784): art/runtime/java_vm_ext.cc:470]   | group="main" sCount=0 dsCount=0 obj=0x12cd4d40 self=0xd68bec00
F/art     (26784): art/runtime/java_vm_ext.cc:470]   | sysTid=27314 nice=0 cgrp=default sched=0/0 handle=0xc816e920
F/art     (26784): art/runtime/java_vm_ext.cc:470]   | state=R schedstat=( 252188581 21615493 235 ) utm=18 stm=7 core=0 HZ=100
F/art     (26784): art/runtime/java_vm_ext.cc:470]   | stack=0xc806c000-0xc806e000 stackSize=1038KB
F/art     (26784): art/runtime/java_vm_ext.cc:470]   | held mutexes= "mutator lock"(shared held)
F/art     (26784): art/runtime/java_vm_ext.cc:470]   native: #00 pc 00351889  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+128)
...
F/art     (26784): art/runtime/java_vm_ext.cc:470]   at com.unity3d.player.UnityPlayer.nativeRender(Native method)
F/art     (26784): art/runtime/java_vm_ext.cc:470]   at com.unity3d.player.UnityPlayer.access$300(unavailable:-1)
F/art     (26784): art/runtime/java_vm_ext.cc:470]   at com.unity3d.player.UnityPlayer$e$1.handleMessage(unavailable:-1)
F/art     (26784): art/runtime/java_vm_ext.cc:470]   at android.os.Handler.dispatchMessage(Handler.java:98)
F/art     (26784): art/runtime/java_vm_ext.cc:470]   at android.os.Looper.loop(Looper.java:154)
F/art     (26784): art/runtime/java_vm_ext.cc:470]   at com.unity3d.player.UnityPlayer$e.run(unavailable:-1)
```
I have tried to find out whether that was my error but that possibility seems unlikely as the same error occurs when starting the example app from the repository. Specifying `safeMode: true` in the widget does not change this behavior either.

I should mention that I needed to adjust my `Build.cs` file as mentioned [here](https://github.com/juicycleff/flutter-unity-view-widget/issues/234#issuecomment-735307249) to run the build successfully. Other than that, I have simply followed the instructions in the `README`. 

Can anyone help? I would really appreciate it!

**Comment by clemens773** [comment]
Update: This was my mistake. When scrolling further up in the Flutter logs, the following message appeared: 
```
E/Unity   ( 6737): Failed to load 'libmain.so'
E/Unity   ( 6737): 
E/Unity   ( 6737): java.lang.UnsatisfiedLinkError: dlopen failed: library "libmain.so" not found
E/Unity   ( 6737): Your hardware does not support this application.
```
On another device, the example worked without an issue.
