### ISSUE TITLE
After Android quits the unity and enters the unity again, it crashes

### ISSUE THREAD

**Issue by 350887156** [juicycleff/flutter-unity-view-widget#357]
>1. flutter screen push to unity screen
>2. unity return flutter 
>3. flutter screen push to unity screen
>4. crash

<details>

```

Launching lib/main.dart on JSN AL00a in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:52326/2jQKqiYmYa8=/ws
I/HwViewRootImpl(19353): removeInvalidNode jank list is null
D/AwareBitmapCacher(19353): handleInit switch not opened pid=19353
W/Settings(19353): Setting device_provisioned has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
V/HiTouch_HiTouchSensor(19353): User setup is finished.
I/flutter (19353): *********************************************
I/flutter (19353):  navigator to next screen
I/flutter (19353): *********************************************
V/AudioManager(19353): querySoundEffectsEnabled...
V/AudioManager(19353): getStreamVolume streamType: 3 volume: 0
V/AudioManager(19353): getStreamVolume streamType: 3 volume: 0
I/Choreographer(19353): Skipped 46 frames!  The application may be doing too much work on its main thread.
I/flutter (19353): *********************************************
I/flutter (19353): ** flutter unity controller setup complete **
I/flutter (19353): *********************************************
I/OpenGLRenderer(19353): Davey! duration=823ms; Flags=1, IntendedVsync=391936959593515, Vsync=391937726260151, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=391937737184984, AnimationStart=391937737326130, PerformTraversalsStart=391937740303734, DrawStart=391937766695921, SyncQueued=391937769581338, SyncStart=391937770250609, IssueDrawCommandsStart=391937770433421, SwapBuffers=391937773643317, FrameCompleted=391937783332380, DequeueBufferDuration=548000, QueueBufferDuration=641000,
W/libEGL  (19353): EGLNativeWindowType 0x721d92c010 disconnect failed
D/mali_winsys(19353): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
W/Gralloc3(19353): allocator 3.x is not supported
D/mali_winsys(19353): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/HwViewRootImpl(19353): removeInvalidNode jank list is null
W/mpany.unityDem(19353): Accessing hidden method Ljava/lang/invoke/MethodHandles$Lookup;-><init>(Ljava/lang/Class;I)V (greylist, reflection, allowed)
W/UnityMain(19353): type=1400 audit(0.0:387632): avc: granted { write } for pid=19353 name="com.DefaultCompany.unityDemo" dev="sdcardfs" ino=9399 scontext=u:r:untrusted_app:s0:c149,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=dir
I/Unity   (19353): SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 8, Memory = 3680mb
I/Unity   (19353): SystemInfo ARM big.LITTLE configuration: 4 big (mask: 0xf0), 4 little (mask: 0xf)
I/Unity   (19353): ApplicationInfo com.DefaultCompany.unityDemo version 1.0.0 build 45171af7-4a01-4c39-b9e2-8a557f1fa834
I/Unity   (19353): Built from '2019.4/china_unity/release' branch, Version '2019.4.4f1 (c74809d26ce9)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Enabled'
W/libEGL  (19353): EGLNativeWindowType 0x726de10f90 disconnect failed
D/mali_winsys(19353): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/mali_winsys(19353): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/vulkan  (19353): searching for layers in '/data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64'
D/vulkan  (19353): searching for layers in '/data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/base.apk!/lib/arm64-v8a'
E/BufferQueueProducer(19353): [ImageReader-1080x2340f1m3-19353-1]:1338: disconnect: not connected (req=1)
W/libEGL  (19353): EGLNativeWindowType 0x71eea8f010 disconnect failed
D/mali_winsys(19353): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/        (19353): PlayerBase::PlayerBase()
D/        (19353): TrackPlayerBase::TrackPlayerBase()
I/libOpenSLES(19353): Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
W/AudioTrack(19353): createTrack_l(0): AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 1924
I/Unity   (19353): Script error: OnTriggerEnter2D
I/Unity   (19353): This message parameter has to be of type: [UNREGISTERED]
I/Unity   (19353): The message will be ignored.
I/Unity   (19353): (Filename: ./Runtime/Mono/MonoScriptCache.cpp Line: 265)
I/Unity   (19353):
V/AudioManager(19353): getStreamVolume streamType: 3 volume: 0
V/MediaRouter(19353): Selecting route: RouteInfo{ name=手机, description=null, status=null, category=RouteCategory{ name=系统 types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
W/UnityMain(19353): type=1400 audit(0.0:387662): avc: granted { read } for pid=19353 name="mscorlib.dll-resources.dat" dev="sdcardfs" ino=1976 scontext=u:r:untrusted_app:s0:c149,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=file
W/UnityMain(19353): type=1400 audit(0.0:387663): avc: granted { read open } for pid=19353 path="/storage/emulated/0/Android/data/com.DefaultCompany.unityDemo/files/il2cpp/Resources/mscorlib.dll-resources.dat" dev="sdcardfs" ino=1976 scontext=u:r:untrusted_app:s0:c149,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=file
W/UnityMain(19353): type=1400 audit(0.0:387664): avc: granted { read } for pid=19353 path="/storage/emulated/0/Android/data/com.DefaultCompany.unityDemo/files/il2cpp/Resources/mscorlib.dll-resources.dat" dev="sdcardfs" ino=1976 scontext=u:r:untrusted_app:s0:c149,c256,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=file
E/Unity   (19353): Unable to open archive file: jar:file:///data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/base.apk!/assets/AssetBundles/Android/manifest
E/Unity   (19353): XAsset.Bundle:OnLoad()
E/Unity   (19353): XAsset.Bundles:LoadInternal(String, Boolean)
E/Unity   (19353): XAsset.Assets:InitializeBundle()
E/Unity   (19353): XAsset.Assets:Creat(String)
E/Unity   (19353): GameMain:Awake()
E/Unity   (19353):
E/Unity   (19353): [ line 599]
E/Unity   (19353): (Filename:  Line: 599)
E/Unity   (19353):
W/libEGL  (19353): EGLNativeWindowType 0x71f771c690 disconnect failed
D/mali_winsys(19353): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
V/AudioManager(19353): getStreamVolume streamType: 3 volume: 0
D/mali_winsys(19353): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/HwViewRootImpl(19353): removeInvalidNode all the node in jank list is out of time
E/BufferQueueProducer(19353): [ImageReader-1080x2255f1m3-19353-3]:1338: disconnect: not connected (req=1)
W/libEGL  (19353): EGLNativeWindowType 0x71ee7a7010 disconnect failed
D/mali_winsys(19353): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/HwViewRootImpl(19353): removeInvalidNode all the node in jank list is out of time
E/BufferQueueProducer(19353): [ImageReader-1080x2340f1m3-19353-4]:1338: disconnect: not connected (req=1)
W/libEGL  (19353): EGLNativeWindowType 0x716ec37010 disconnect failed
D/mali_winsys(19353): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
E/Surface (19353): getSlotFromBufferLocked: unknown buffer: 0x7142630700
E/vulkan  (19353): queueBuffer failed: Invalid argument (-22)
E/vulkan  (19353): native_window_api_connect() failed: No such device (-19)
E/CRASH   (19353): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
E/CRASH   (19353): Version '2019.4.4f1 (c74809d26ce9)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
E/CRASH   (19353): Build fingerprint: 'HONOR/JSN-AL00a/HWJSN-HM:10/HONORJSN-AL00a/10.0.0.168C00:user/release-keys'
E/CRASH   (19353): Revision: '0'
E/CRASH   (19353): ABI: 'arm64'
E/CRASH   (19353): Timestamp: 2021-03-22 18:16:34+0800
E/CRASH   (19353): pid: 19353, tid: 19482, name: UnityGfxDeviceW  >>> com.DefaultCompany.unityDemo <<<
E/CRASH   (19353): uid: 10149
E/CRASH   (19353): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
E/CRASH   (19353): Cause: null pointer dereference
E/CRASH   (19353):     x0  000000727c62e228  x1  0000000000000000  x2  000000714d1817f0  x3  0000000000000002
E/CRASH   (19353):     x4  00000000000001b4  x5  0000400800000000  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
E/CRASH   (19353):     x8  0000000000000001  x9  7e23814c1b1fb298  x10 00000000000001b4  x11 0000000000000000
E/CRASH   (19353):     x12 0101010101010101  x13 0000000000000003  x14 0000000000000002  x15 00001758de1ff0b3
E/CRASH   (19353):     x16 0000007309bae938  x17 0000007309ba2970  x18 00000000ac3b7fa9  x19 0000000000000000
E/CRASH   (19353):     x20 000000714d1817f0  x21 000000727c62e200  x22 000000714d182020  x23 000000730d6fa0a0
E/CRASH   (19353):     x24 000000730d6f7028  x25 000000716ebc3410  x26 0000000000010dd8  x27 00000071e0070c10
E/CRASH   (19353):     x28 000000716ebc3108  x29 000000714d1817c0
E/CRASH   (19353):     sp  000000714d181770  lr  00000071f6797ca4  pc  000000730b736368
E/CRASH   (19353):
E/CRASH   (19353): backtrace:
E/CRASH   (19353):       #00 pc 0000000000020368  /system/lib64/libvulkan.so (BuildId: d54ca68d921738dec67288e32448e333)
E/CRASH   (19353):       #01 pc 00000000003bbca0  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/CRASH   (19353):       #02 pc 00000000003bc194  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/CRASH   (19353):       #03 pc 00000000003bf180  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/CRASH   (19353):       #04 pc 000000000039e304  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/CRASH   (19353):       #05 pc 000000000071e1dc  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/CRASH   (19353):       #06 pc 000000000071edf8  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/CRASH   (19353):       #07 pc 00000000007162b0  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/CRASH   (19353):       #08 pc 000000000029bcc8  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/CRASH   (19353):       #09 pc 00000000000ce1b0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 736a6b327ce386a8cddaf85ea68bf6ea)
E/CRASH   (19353):       #10 pc 0000000000070ba8  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 736a6b327ce386a8cddaf85ea68bf6ea)
I/flutter (19353): *********************************************
I/flutter (19353):  navigator to next screen
I/flutter (19353): *********************************************
V/AudioManager(19353): querySoundEffectsEnabled...
I/flutter (19353): *********************************************
I/flutter (19353): ** flutter unity controller setup complete **
I/flutter (19353): *********************************************
W/libEGL  (19353): EGLNativeWindowType 0x721d92c010 disconnect failed
D/mali_winsys(19353): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
E/CRASH   (19353): other thread is trapped; signum = 11
I/QarthLog(19353): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(19353): [PatchStore] create disable file for com.DefaultCompany.unityDemo uid is 10149
E/AndroidRuntime(19353): FATAL EXCEPTION: UnityMain
E/AndroidRuntime(19353): Process: com.DefaultCompany.unityDemo, PID: 19353
E/AndroidRuntime(19353): java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
E/AndroidRuntime(19353): Version '2019.4.4f1 (c74809d26ce9)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
E/AndroidRuntime(19353): Build fingerprint: 'HONOR/JSN-AL00a/HWJSN-HM:10/HONORJSN-AL00a/10.0.0.168C00:user/release-keys'
E/AndroidRuntime(19353): Revision: '0'
E/AndroidRuntime(19353): ABI: 'arm64'
E/AndroidRuntime(19353): Timestamp: 2021-03-22 18:16:34+0800
E/AndroidRuntime(19353): pid: 19353, tid: 19482, name: UnityGfxDeviceW  >>> com.DefaultCompany.unityDemo <<<
E/AndroidRuntime(19353): uid: 10149
E/AndroidRuntime(19353): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
E/AndroidRuntime(19353): Cause: null pointer dereference
E/AndroidRuntime(19353):     x0  000000727c62e228  x1  0000000000000000  x2  000000714d1817f0  x3  0000000000000002
E/AndroidRuntime(19353):     x4  00000000000001b4  x5  0000400800000000  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
E/AndroidRuntime(19353):     x8  0000000000000001  x9  7e23814c1b1fb298  x10 00000000000001b4  x11 0000000000000000
E/AndroidRuntime(19353):     x12 0101010101010101  x13 0000000000000003  x14 0000000000000002  x15 00001758de1ff0b3
E/AndroidRuntime(19353):     x16 0000007309bae938  x17 0000007309ba2970  x18 00000000ac3b7fa9  x19 0000000000000000
E/AndroidRuntime(19353):     x20 000000714d1817f0  x21 000000727c62e200  x22 000000714d182020  x23 000000730d6fa0a0
E/AndroidRuntime(19353):     x24 000000730d6f7028  x25 000000716ebc3410  x26 0000000000010dd8  x27 00000071e0070c10
E/AndroidRuntime(19353):     x28 000000716ebc3108  x29 000000714d1817c0
E/AndroidRuntime(19353):     sp  000000714d181770  lr  00000071f6797ca4  pc  000000730b736368
E/AndroidRuntime(19353):
E/AndroidRuntime(19353): backtrace:
E/AndroidRuntime(19353):       #00 pc 0000000000020368  /system/lib64/libvulkan.so (BuildId: d54ca68d921738dec67288e32448e333)
E/AndroidRuntime(19353):       #01 pc 00000000003bbca0  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/AndroidRuntime(19353):       #02 pc 00000000003bc194  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/AndroidRuntime(19353):       #03 pc 00000000003bf180  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/AndroidRuntime(19353):       #04 pc 000000000039e304  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/AndroidRuntime(19353):       #05 pc 000000000071e1dc  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/AndroidRuntime(19353):       #06 pc 000000000071edf8  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/AndroidRuntime(19353):       #07 pc 00000000007162b0  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/AndroidRuntime(19353):       #08 pc 000000000029bcc8  /data/app/com.DefaultCompany.unityDemo-DqpSFdHIN4KG9c34ueb6QA==/lib/arm64/libunity.so (BuildId: d883af82999a503de1be76ca27201c9d7cc12690)
E/AndroidRuntime(19353):       #09 pc 00000000000ce1b0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 736a6b327ce386a8cddaf85ea68bf6ea)
E/AndroidRuntime(19353):       #10 pc 0000000000070ba8  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 736a6b327ce386a8cddaf85ea68bf6ea)
E/AndroidRuntime(19353):
E/AndroidRuntime(19353): 	at libvulkan.0x20368(Native Method)
E/AndroidRuntime(19353): 	at libunity.0x3bbca0(Native Method)
E/AndroidRuntime(19353): 	at libunity.0x3bc194(Native Method)
E/AndroidRuntime(19353): 	at libunity.0x3bf180(Native Method)
E/AndroidRuntime(19353): 	at libunity.0x39e304(Native Method)
E/AndroidRuntime(19353): 	at libunity.0x71e1dc(Native Method)
E/AndroidRuntime(19353): 	at libunity.0x71edf8(Native Method)
E/AndroidRuntime(19353): 	at libunity.0x7162b0(Native Method)
E/AndroidRuntime(19353): 	at libunity.0x29bcc8(Native Method)
E/AndroidRuntime(19353): 	at libc.__pthread_start(void*)(__pthread_start:36)
E/AndroidRuntime(19353): 	at libc.__start_thread(__start_thread:64)
I/Process (19353): Sending signal. PID: 19353 SIG: 9
Lost connection to device.
Exited (sigterm)


```

</details>

### flutter doctor -v

<details>

```
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.1 20D75 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.2 at /Users/v123456/development/flutter
    • Framework revision 8962f6dc68 (11 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/v123456/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • JSN AL00a (mobile) • 2NJ4C19505000253 • android-arm64  • Android 10 (API 29)
    • Chrome (web)       • chrome           • web-javascript • Google Chrome 89.0.4389.90
    
```

</details>

### code

<details>

```
import 'package:flutter/material.dart';
import 'package:flutter_unity_widget/flutter_unity_widget.dart';

class UnityDemoScreen extends StatefulWidget {
  UnityDemoScreen({Key key}) : super(key: key);

  @override
  _UnityDemoScreenState createState() => _UnityDemoScreenState();
}

class _UnityDemoScreenState extends State<UnityDemoScreen> {
  UnityWidgetController _unityWidgetController;

  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        top: false,
        child: WillPopScope(
          onWillPop: () async {
            return true;
          },
          child: UnityWidget(
            onUnityCreated: onUnityCreated,
          ),
        ),
      ),
    );
  }

  // Callback that connects the created controller to the unity controller
  void onUnityCreated(controller) {
    this._unityWidgetController = controller;
  }

  @override
  void dispose() {
    super.dispose();
    _unityWidgetController?.dispose();
  }
}


```

</details>

**Comment by 350887156** [comment]
Crash caused by misconfiguration of unity

**Comment by zhanghuidong1** [comment]
19/5000 
Can you tell me the specific reason? I have the same problem

**Comment by zhanghuidong1** [comment]
> unity 配置错误导致的崩溃

你能告诉我具体的原因吗？我也有同样的问题
