### ISSUE TITLE
couldn't find "libmain.so"   can anyone help me?

### ISSUE THREAD

**Issue by shubham8170** [juicycleff/flutter-unity-view-widget#467]
D/eglCodecCommon( 8764): setVertexArrayObject: set vao to 0 (0) 1 0
E/Unity   ( 8764): Failed to load 'libmain.so', the application will terminate.
D/AndroidRuntime( 8764): Shutting down VM
E/AndroidRuntime( 8764): FATAL EXCEPTION: main
E/AndroidRuntime( 8764): Process: com.example.example, PID: 8764
E/AndroidRuntime( 8764): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.example-G4lHbkVdGhJdgC7zUZZHig==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.example-G4lHbkVdGhJdgC7zUZZHig==/lib/x86, /data/app/com.example.example-G4lHbkVdGhJdgC7zUZZHig==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libmain.so"
E/AndroidRuntime( 8764): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
E/AndroidRuntime( 8764): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/AndroidRuntime( 8764): 	at java.lang.System.loadLibrary(System.java:1667)
E/And

**Comment by adam-fu** [comment]
Hi @shubham8170 ,
I run in the same error when I wanted to run on Android Emulator on Ubuntu. It worked for me when using my physical device.

**Comment by adam-fu** [comment]
Having a closer look I see that my android emulator runs with x86, that is not supported in unity anymore: https://answers.unity.com/questions/1630396/unity-build-for-android-x86-64.html

the generated ./android/unityLibrary/gradle.build contains:
```
    defaultConfig {
       ...
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
        ```
        My emulator runs with x86, so adding  the abiFilters in my ./andorid/app.build.grade to:
        
        ```    ndk {
        abiFilters 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'arm64-v8a'
    }
    ``` will not help, as x86 is not included by unity.
    
    So in my case setting the abiFilters in android/app/build.gradle to:
    ```
    android {
      defaultConfig {
        ... // target version 29 or 30
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
      }
    }
        ```
    makes it run on the real device.

**Comment by juicycleff** [comment]
@shubham8170 please change your Unity scripting engine to IL2CPP and your ndk dir to your flutter app local.properties 

`ndk.dir=C:\\Users\\<Your PC>\\AppData\\Local\\Android\\sdk\\ndk\\20.0.5594570`

**Comment by Ahmadre** [comment]
> @shubham8170 please change your Unity scripting engine to IL2CPP and your ndk dir to your flutter app local.properties
> 
> `ndk.dir=C:\\Users\\<Your PC>\\AppData\\Local\\Android\\sdk\\ndk\\20.0.5594570`

This is missing in the actual docs.

**Comment by wzlsquall** [comment]
Just add this attribute to your **AndroidManifest.xml**
`android:extractNativeLibs="true"`
