### ISSUE TITLE
Web MissingPluginException(No implementation found for method unity#resumePlayer on channel plugin.xraph.com/unity_view)

### ISSUE THREAD

**Issue by Ortes** [juicycleff/flutter-unity-view-widget#597]
Example project is throwing exception: MissingPluginException(No implementation found for method unity#resumePlayer on channel plugin.xraph.com/unity_view) on chrome when displaying UnityWidget.
Release build does not resolve the issue.
If i miss some steps in the web setup could you provide those ?

Have a nice day :)

- Build unity
- cd in the example project
- `flutter run -d chrome`
- Click on Simple Unity Demo
- Widget crash

Unity:
 - Version 2022.1.2f1
 - OS Linux
 - Export WebGL
 
Flutter
- 2.10.5

Stack trace:
Error: MissingPluginException(No implementation found for method unity#resumePlayer on channel plugin.xraph.com/unity_view)
    at Object.throw_ [as throw] (http://localhost:33771/dart_sdk.js:5391:11)
    at platform_channel.MethodChannel.new._invokeMethod (http://localhost:33771/packages/flutter/src/services/restoration.dart.lib.js:1611:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:33771/dart_sdk.js:42993:33
    at _RootZone.runUnary (http://localhost:33771/dart_sdk.js:42849:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:33771/dart_sdk.js:37417:29)
    at handleValueCallback (http://localhost:33771/dart_sdk.js:38020:49)
    at Function._propagateToListeners (http://localhost:33771/dart_sdk.js:38058:17)
    at _Future.new.[_completeWithValue] (http://localhost:33771/dart_sdk.js:37900:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:33771/dart_sdk.js:37923:35)
    at Object._microtaskLoop (http://localhost:33771/dart_sdk.js:43153:13)
    at _startMicrotaskLoop (http://localhost:33771/dart_sdk.js:43159:13)
    at http://localhost:33771/dart_sdk.js:38289:9

**Comment by Ahmadre** [comment]
Follow and upvote these Fixes:
- https://github.com/juicycleff/flutter-unity-view-widget/pull/616
- https://github.com/juicycleff/flutter-unity-view-widget/pull/617
- https://github.com/juicycleff/flutter-unity-view-widget/pull/618
