### ISSUE TITLE
[ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.

### ISSUE THREAD

**Issue by Samuel310** [juicycleff/flutter-unity-view-widget#642]
App crashes in release mode, while launching unity view.

```
E/flutter (31736): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
E/flutter (31736):      at f.a.c.d.m.G(Unknown Source:100)
E/flutter (31736):      at f.a.c.d.m.Q(Unknown Source:3)
E/flutter (31736):      at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(Unknown Source:19)
E/flutter (31736):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (31736):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (31736):      at android.os.Looper.loop(Looper.java:193)
E/flutter (31736):      at android.app.ActivityThread.main(ActivityThread.java:7861)
E/flutter (31736):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (31736):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
E/flutter (31736):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/flutter (31736): 
F/flutter (31736): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1469)] Check failed: fml::jni::CheckException(env). 
```

**Comment by IluhinDotPro** [comment]
**flutter channel master**

Switching to flutter channel 'master'...
git: Branch 'master' set up to track remote branch 'master' from 'origin'.
git: Switched to a new branch 'master'
Successfully switched to flutter channel 'master'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'

**flutter upgrade**
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 3a193e9f38a274c7d0d1b65c02c1b4247d4e2384...
Expanding downloaded archive...
Building flutter tool...
Running pub upgrade...
Flutter is already up to date on channel master
Flutter 3.1.0-0.0.pre.1620 • channel master • https://github.com/flutter/flutter.git
Framework • revision b6bf7e5190 (19 minutes ago) • 2022-07-12 13:30:08 -0400
Engine • revision 3a193e9f38
Tools • Dart 2.18.0 (build 2.18.0-271.0.dev) • DevTools 2.15.0
===============
After that issue was fixed
