### ISSUE TITLE
White screen while launching

### ISSUE THREAD

**Issue by virtyos** [juicycleff/flutter-unity-view-widget#663]
Android release build is not working. I see a white screen after launching the app. Logs are empty.

**Comment by dawiddszewczyk** [comment]
@virtyos  Can you put required information like in template of issue? Like unity version, flutter unity widget version ect?
Its seem to be the same error like in this issue.
https://github.com/juicycleff/flutter-unity-view-widget/issues/650#issue-1299450995
@Ahmadre @juicycleff

**Comment by virtyos** [comment]
@dawiddszewczyk checked on several devices, result the same
in logs I'm getting such messages

```
2022-07-24 04:35:34.510 24170-24182/? W/System: A resource failed to call release. 
2022-07-24 04:35:34.510 24170-24182/? W/System: A resource failed to call release.  
```

**Comment by virtyos** [comment]
debug version works perfectly

**Comment by virtyos** [comment]
Sometimes I even dont see white screen and the app crashes immediately after launch.
In that case there are such messages 

```
2022-07-24 04:41:41.597 26172-26172/? E/flutter: [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.IllegalStateException: Platform view hasn't been initialized from the platform view channel.
        at g1.l.I(Unknown Source:100)
        at g1.l.Q(Unknown Source:3)
        at io.flutter.embedding.engine.FlutterJNI.onDisplayPlatformView(Unknown Source:19)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:339)
        at android.os.Looper.loopOnce(Looper.java:186)
        at android.os.Looper.loop(Looper.java:334)
        at android.app.ActivityThread.main(ActivityThread.java:8333)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
2022-07-24 04:41:41.597 26172-26172/? A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1469)] Check failed: fml::jni::CheckException(env). 
2022-07-24 04:41:41.597 26172-26172/? A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 26172 (com.sl.avatar), pid 26172 (com.sl.avatar)
2022-07-24 04:41:41.843 26260-26260/? A/DEBUG: Softversion: PD2107F_EX_A_6.7.1
2022-07-24 04:41:41.843 26260-26260/? A/DEBUG: Time: 2022-07-24 04:41:41
2022-07-24 04:41:41.843 26260-26260/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2022-07-24 04:41:41.843 26260-26260/? A/DEBUG: Build fingerprint: 'vivo/2061_RU/2061:12/SP1A.210812.003/compiler06171520:user/release-keys'
2022-07-24 04:41:41.843 26260-26260/? A/DEBUG: Revision: '0'
2022-07-24 04:41:41.843 26260-26260/? A/DEBUG: ABI: 'arm64'
2022-07-24 04:41:41.843 26260-26260/? A/DEBUG: Timestamp: 2022-07-24 04:41:41.679502505+0300
2022-07-24 04:41:41.843 26260-26260/? A/DEBUG: Process uptime: 0s
2022-07-24 04:41:41.843 26260-26260/? A/DEBUG: Cmdline: com.sl.avatar
2022-07-24 04:41:41.843 26260-26260/? A/DEBUG: pid: 26172, tid: 26172, name: com.sl.avatar  >>> com.sl.avatar <<<
2022-07-24 04:41:41.843 26260-26260/? A/DEBUG: uid: 10380
2022-07-24 04:41:41.843 26260-26260/? A/DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
2022-07-24 04:41:41.843 26260-26260/? A/DEBUG: Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1469)] Check failed: fml::jni::CheckException(env). 
    '
```

**Comment by virtyos** [comment]
also we have these warnings during the build process

```
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    C:/Users/virty/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.30/5fd47535cc85f9e24996f939c2de6583991481b0/kotlin-stdlib-jdk8-1.5.30.jar (version 1.5)
    C:/Users/virty/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.20/f8629f336bad4001c89e9cffa5ef3d4b5d0f5e22/kotlin-stdlib-jdk7-1.6.20.jar (version 1.6)
    C:/Users/virty/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.21/11ef67f1900634fd951bad28c53ec957fabbe5b8/kotlin-stdlib-1.6.21.jar (version 1.6)
    C:/Users/virty/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.21/5e5b55c26dbc80372a920aef60eb774b714559b8/kotlin-stdlib-common-1.6.21.jar (version 1.6)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
[CXX1104] NDK from ndk.dir at C:\Program Files\Unity\Hub\Editor\2021.3.6f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK had version [21.3.6528147] which disagrees with android.ndkVersion [21.1.6352462]
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    C:/Users/virty/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.5.30/5fd47535cc85f9e24996f939c2de6583991481b0/kotlin-stdlib-jdk8-1.5.30.jar (version 1.5)
    C:/Users/virty/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.6.20/f8629f336bad4001c89e9cffa5ef3d4b5d0f5e22/kotlin-stdlib-jdk7-1.6.20.jar (version 1.6)
    C:/Users/virty/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.6.21/11ef67f1900634fd951bad28c53ec957fabbe5b8/kotlin-stdlib-1.6.21.jar (version 1.6)
    C:/Users/virty/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.6.21/5e5b55c26dbc80372a920aef60eb774b714559b8/kotlin-stdlib-common-1.6.21.jar (version 1.6)
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath
[CXX1104] NDK from ndk.dir at C:\Program Files\Unity\Hub\Editor\2021.3.6f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK had version [21.3.6528147] which disagrees with android.ndkVersion [21.1.6352462]
```

**Comment by virtyos** [comment]
Finally I resilved the issue by adding 

```
    buildTypes {
        release {
           ...
	    minifyEnabled false
            shrinkResources false
        }
    }
```

to build.gradle. It's something about wrong minifing

**Comment by ama22ni** [comment]
@virtyos I tried you solution but it didn't work , is there any other solution ? :(
