### ISSUE TITLE
Execution failed for task ':unityLibrary:BuildIl2CppTask'.

### ISSUE THREAD

**Issue by DeliriousLee** [juicycleff/flutter-unity-view-widget#675]
> Hello @phamtuongvan
> 
> ```
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> > A problem occurred starting process 'command '/Users/abhishek/Downloads/flutterunity/android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/build/deploy/netcoreapp3.1/il2cpp.exe''
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 47s
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)
> ```
> 
> I am getting this error. So what should I do?

I get the same error, too.

unity version: 2020.2.2.1f1
gradle version: 5.6.4

_Originally posted by @jsolra in https://github.com/juicycleff/flutter-unity-view-widget/issues/273#issuecomment-881213928_

**Comment by DeliriousLee** [comment]
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Building libil2cpp.so with AndroidToolChain
	Output directory: /Users/mac/Work/project/ant_meta_universe/android/unityLibrary/src/main/jniLibs/armeabi-v7a
	Cache directory: /Users/mac/Work/project/ant_meta_universe/android/unityLibrary/build/il2cpp_armeabi-v7a_Release/il2cpp_cache
Error: System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Unity.IL2CPP.Shell.SetupAndStart(ExecuteContext context, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 423
   at Unity.IL2CPP.Shell.ExecuteAsync(ExecuteArgs executeArgs, IExecuteController controller, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 299
   at Unity.IL2CPP.Shell.Execute(ExecuteArgs executeArgs, IExecuteController controller) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 355
   at Unity.IL2CPP.Building.CppProgramBuilder.ProvideObjectFile(IntermediateObjectFileCompilationData data) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/CppProgramBuilder.cs:line 331
   at Unity.IL2CPP.Building.ParallelFor.<>c__DisplayClass1_0`2.<RunWithResult>b__0(Object o) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/ParallelFor.cs:line 78
Error: System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Unity.IL2CPP.Shell.SetupAndStart(ExecuteContext context, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 423
   at Unity.IL2CPP.Shell.ExecuteAsync(ExecuteArgs executeArgs, IExecuteController controller, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 299
   at Unity.IL2CPP.Shell.Execute(ExecuteArgs executeArgs, IExecuteController controller) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 355
   at Unity.IL2CPP.Building.CppProgramBuilder.ProvideObjectFile(IntermediateObjectFileCompilationData data) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/CppProgramBuilder.cs:line 331
   at Unity.IL2CPP.Building.ParallelFor.<>c__DisplayClass1_0`2.<RunWithResult>b__0(Object o) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/ParallelFor.cs:line 78
Error: System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Unity.IL2CPP.Shell.SetupAndStart(ExecuteContext context, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 423
   at Unity.IL2CPP.Shell.ExecuteAsync(ExecuteArgs executeArgs, IExecuteController controller, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 299
   at Unity.IL2CPP.Shell.Execute(ExecuteArgs executeArgs, IExecuteController controller) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 355
   at Unity.IL2CPP.Building.CppProgramBuilder.ProvideObjectFile(IntermediateObjectFileCompilationData data) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/CppProgramBuilder.cs:line 331
   at Unity.IL2CPP.Building.ParallelFor.<>c__DisplayClass1_0`2.<RunWithResult>b__0(Object o) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/ParallelFor.cs:line 78
Error: System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Unity.IL2CPP.Shell.SetupAndStart(ExecuteContext context, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 423
   at Unity.IL2CPP.Shell.ExecuteAsync(ExecuteArgs executeArgs, IExecuteController controller, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 299
   at Unity.IL2CPP.Shell.Execute(ExecuteArgs executeArgs, IExecuteController controller) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 355
   at Unity.IL2CPP.Building.CppProgramBuilder.ProvideObjectFile(IntermediateObjectFileCompilationData data) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/CppProgramBuilder.cs:line 331
   at Unity.IL2CPP.Building.ParallelFor.<>c__DisplayClass1_0`2.<RunWithResult>b__0(Object o) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/ParallelFor.cs:line 78
Error: System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Unity.IL2CPP.Shell.SetupAndStart(ExecuteContext context, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 423
   at Unity.IL2CPP.Shell.ExecuteAsync(ExecuteArgs executeArgs, IExecuteController controller, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 299
   at Unity.IL2CPP.Shell.Execute(ExecuteArgs executeArgs, IExecuteController controller) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 355
   at Unity.IL2CPP.Building.CppProgramBuilder.ProvideObjectFile(IntermediateObjectFileCompilationData data) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/CppProgramBuilder.cs:line 331
   at Unity.IL2CPP.Building.ParallelFor.<>c__DisplayClass1_0`2.<RunWithResult>b__0(Object o) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/ParallelFor.cs:line 78
Error: System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Unity.IL2CPP.Shell.SetupAndStart(ExecuteContext context, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 423
   at Unity.IL2CPP.Shell.ExecuteAsync(ExecuteArgs executeArgs, IExecuteController controller, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 299
   at Unity.IL2CPP.Shell.Execute(ExecuteArgs executeArgs, IExecuteController controller) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 355
   at Unity.IL2CPP.Building.CppProgramBuilder.ProvideObjectFile(IntermediateObjectFileCompilationData data) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/CppProgramBuilder.cs:line 331
   at Unity.IL2CPP.Building.ParallelFor.<>c__DisplayClass1_0`2.<RunWithResult>b__0(Object o) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/ParallelFor.cs:line 78
Error: System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Unity.IL2CPP.Shell.SetupAndStart(ExecuteContext context, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 423
   at Unity.IL2CPP.Shell.ExecuteAsync(ExecuteArgs executeArgs, IExecuteController controller, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 299
   at Unity.IL2CPP.Shell.Execute(ExecuteArgs executeArgs, IExecuteController controller) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 355
   at Unity.IL2CPP.Building.CppProgramBuilder.ProvideObjectFile(IntermediateObjectFileCompilationData data) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/CppProgramBuilder.cs:line 331
   at Unity.IL2CPP.Building.ParallelFor.<>c__DisplayClass1_0`2.<RunWithResult>b__0(Object o) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/ParallelFor.cs:line 78
Error: System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Unity.IL2CPP.Shell.SetupAndStart(ExecuteContext context, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 423
   at Unity.IL2CPP.Shell.ExecuteAsync(ExecuteArgs executeArgs, IExecuteController controller, Boolean asyncMode) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 299
   at Unity.IL2CPP.Shell.Execute(ExecuteArgs executeArgs, IExecuteController controller) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Shell/Shell.cs:line 355
   at Unity.IL2CPP.Building.CppProgramBuilder.ProvideObjectFile(IntermediateObjectFileCompilationData data) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/CppProgramBuilder.cs:line 331
   at Unity.IL2CPP.Building.ParallelFor.<>c__DisplayClass1_0`2.<RunWithResult>b__0(Object o) in /Users/bokken/build/output/fmwang/il2cpp/Unity.IL2CPP.Building/ParallelFor.cs:line 78

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/mac/Work/project/ant_meta_universe/android/unityLibrary/build.gradle' line: 53

* What went wrong:
Execution failed for task ':unityLibrary:BuildIl2CppTask'.
> Process 'command '/Users/mac/Work/project/ant_meta_universe/android/unityLibrary/src/main/Il2CppOutputProject/IL2CPP/build/deploy/netcoreapp3.1/il2cpp'' finished with non-zero exit value 255

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 58s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**Comment by DeliriousLee** [comment]
I used Unity 2022.1.13f1, fuw-2022.1.1-v2.unitypackage. resolved it.
I used android-ndk-r21d as ndk, and need to add darwin-x86_64 under /Users/mac/Work/resource/android-ndk-r21d/toolchains/llvm/prebuilt directory, this file needs to be downloaded from other websites, the same Do the same in the /Users/mac/Work/resource/android-ndk-r21d/prebuilt/darwin-x86_64 directory
