### ISSUE TITLE
libmain.so not found

### ISSUE THREAD

**Issue by soma9017** [juicycleff/flutter-unity-view-widget#866]
**Describe the bug**
libmain.so is not found error is found while building debug apk, it works fine building in release apk 

**To Reproduce**
1. Go to flutter and start building the apk using debug mode
2. Click on run
3. Scroll down to start debugging

Launching lib\main.dart on Android SDK built for x86 in debug mode...
main.dart:1
√  Built build\app\outputs\flutter-apk\app-debug.apk.
E/FlutterLoader( 4475): Flutter initialization failed.
E/FlutterLoader( 4475): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader( 4475): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
E/FlutterLoader( 4475): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)

**Comment by timbotimbo** [comment]
You are either targeting and emulator or somehow have the x86 target included in your build.

The unity export does not support x86 mode.
Check the emulator section in the readme for more context.
