### ISSUE TITLE
 Failed to handle method call : java.lang.NullPointerException

### ISSUE THREAD

**Issue by chetu-ko** [juicycleff/flutter-unity-view-widget#984]
**The bug**
The export and flutter build is successful after that, we are getting a yellow screen error on the screen both the real device and the emulator device. 

[ScreenShot](https://github.com/user-attachments/assets/feb87be7-497b-46cb-b22f-a0776980cb28)
 
**Error log**

>E/MethodChannel#flutter/platform_views(10293): Failed to handle method call
E/MethodChannel#flutter/platform_views(10293): java.lang.NullPointerException
E/MethodChannel#flutter/platform_views(10293): 	at com.xraph.plugin.flutter_unity_widget.FlutterUnityWidgetController.reattachToView(FlutterUnityWidgetController.kt:359)
E/MethodChannel#flutter/platform_views(10293): 	at com.xraph.plugin.flutter_unity_widget.FlutterUnityWidgetController.onResume(FlutterUnityWidgetController.kt:238)
E/MethodChannel#flutter/platform_views(10293): 	at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:42)
E/MethodChannel#flutter/platform_views(10293): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
E/MethodChannel#flutter/platform_views(10293): 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:202)
E/MethodChannel#flutter/platform_views(10293): 	at com.xraph.plugin.flutter_unity_widget.FlutterUnityWidgetController.bootstrap(FlutterUnityWidgetController.kt:265)
E/MethodChannel#flutter/platform_views(10293): 	at com.xraph.plugin.flutter_unity_widget.FlutterUnityWidgetBuilder.build(FlutterUnityWidgetBuilder.kt:22)
E/MethodChannel#flutter/platform_views(10293): 	at com.xraph.plugin.flutter_unity_widget.FlutterUnityWidgetFactory.create(FlutterUnityWidgetFactory.kt:34)
E/MethodChannel#flutter/platform_views(10293): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:527)
E/MethodChannel#flutter/platform_views(10293): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:199)
E/MethodChannel#flutter/platform_views(10293): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
E/MethodChannel#flutter/platform_views(10293): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/MethodChannel#flutter/platform_views(10293): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter/platform_views(10293): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter/platform_views(10293): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views(10293): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views(10293): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#flutter/platform_views(10293): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views(10293): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#flutter/platform_views(10293): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#flutter/platform_views(10293): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/MethodChannel#flutter/platform_views(10293): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(10293): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#flutter/platform_views(10293): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/OpenGLRenderer(10293): Unable to match the desired swap behavior.
E/flutter (10293): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException

Please help us with the issue. I don't know if the above log works to debug the issue, but this is what I am getting in the debug logger. Let me know if any other details are needed.

To see the versions used please refer #981 

Thank you.

**Comment by timbotimbo** [comment]
- Just to confirm the versions mentioned in the other issue, are you now using Unity 2022.3.43f1 instead of 2023?

>  Flutter: 3.19.2
    Gradle:
    Distribution URL: Distribution https://services.gradle.org/distributions/gradle-7.6-bin.zip
    Classpath: classpath 'com.android.tools.build:gradle:7.3.1'
    Kotlin Version: ext.kotlin_version = '1.9.0'
    Unity: 2023.2.20f
    minSdkVersion: 26
    targetSdkVersion: 34
    
- Are you using the `useAndroidViewSurface` (true or false) parameter in the UnityWidget?
I'm asking because Flutter 3.19 has [invisibility](https://github.com/juicycleff/flutter-unity-view-widget/issues/912) and [transition/resize](https://github.com/juicycleff/flutter-unity-view-widget/issues/929) issues when this param is false.
If you are not using AR, using Flutter 3.22+ will help in preventing a lot of small issues.

- Can you replicate this with the example project?
  Just to check if it is anything specific to your dart code or not.

**Comment by chetu-ko** [comment]
1. Yes, I am using the unity version 2022.3.43f1.
2. No I have not used true/false parameter in UnityWidget.
3. I tried running example, It's working fine with all configuration.

**Comment by chetu-ko** [comment]
Hi @timbotimbo 
I am now getting a different error, I am using Android> 10, and I upgraded my Flutter version to 3.24 to the recent version, This time not even the Flutter build is completed.

I checked the issue I have not found the same issue in the issue list, Can you please tag if any issue is already listed and solved?

> e: file:///Users/chetan/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.1/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetPlugin.kt:97:9 Cannot weaken access privilege 'public' for 'lifecycle' in 'LifecycleOwner'
e: file:///Users/chetan/.pub-cache/hosted/pub.dev/flutter_unity_widget-2022.2.1/android/src/main/kotlin/com/xraph/plugin/flutter_unity_widget/FlutterUnityWidgetPlugin.kt:97:21 'lifecycle' hides member of supertype 'LifecycleOwner' and needs 'override' modifier

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_unity_widget:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by timbotimbo** [comment]
Looks like https://github.com/juicycleff/flutter-unity-view-widget/issues/973

**Comment by chetu-ko** [comment]
HI @timbotimbo.

I have configured everything, and I did every step you told me, but I am still getting the same error,  and the black screen once the build is successful, Please help me to fix this. Also, I have tried adding a `useAndroidViewSurface` true or false but still not working tried flutter clean.


Android > 10
flutter 3.24.0
unity 2022.3.43f1.
package 
```
  flutter_unity_widget:
      git:
        url: https://github.com/juicycleff/flutter-unity-view-widget.git
        ref: flutter_3.24_android_hotfix
```
ERROR:
> java.lang.NullPointerException

https://github.com/juicycleff/flutter-unity-view-widget/issues/984#issue-2515875345

**Comment by emileswain** [comment]
i'm dealing with multiple errors, but I believe that the following fixed an issue that threw this error, `.FlutterUnityWidgetController.reattachToView` I'm adding this comment to help others deal with unity/flutter version upgrades where you often end up here again and again. 

Adding `<string name="game_view_content_description">Game view</string>` to the `andoird/app/src/main/res/values/styles.xml` fixed the issue for me. (solution related to UAAL [here](https://discussions.unity.com/t/unity-2018-3-6-upgrade-to-unity-2018-4-has-bug/744165) )

I personaly believe that the `.FlutterUnityWidgetController.reattachToView` error is reflecting the fact that something else went horribly wrong at a low level, and this is where the error surfaces to the user. I.e. its not really anthing to do with reattachToView. For example, requesting an android res that doesn't exist isn't being handled very well.

**Comment by timbotimbo** [comment]
If this is indeed relevant, I think it should be strings.xml instead fo styles. 
(Like mentined before here https://github.com/juicycleff/flutter-unity-view-widget/issues/516#issuecomment-1014989976)

**Comment by chetu-ko** [comment]
@emileswain Thank you for the response, but this doesn't solve any of my problems. Please check if I am adding it in right way.

<img width="826" alt="Screenshot 2024-09-19 at 3 12 47 PM" src="https://github.com/user-attachments/assets/12045e37-bedc-4ee6-9d67-f69e81af8d4b">

**Comment by emileswain** [comment]
strictly speaking it should go into the `android/app/src/main/res/values/strings.xml` create the strings.xml file if it doesn't exist.  For example .... you may not need the app_name field. 
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <string name="app_name">DemoURPTemplate</string>
  <string name="game_view_content_description">Game view</string>
</resources>
```
This may be unrelated, its just the error is pretty similar to what i had when this element was missing. Also if you have values-night, make sure its in there as well.

**Comment by chetu-ko** [comment]
@emileswain Thank you, I have tried everything. I don't know, why it is not running. I have added the same thing in the path `android/app/src/main/res/values/strings.xml` path and tried everything after adding that.

Flutter clean
Pub cache repair
fluteter_unity_widget: 2022.0, 2, flutter_3.24_android_hotfix

I tried all the versions of packages by running all the above functions, but it's giving the same error every time I run the Flutter project, I am not sure why it's not working.
